import { Component, HostListener, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AgGridAngular, AgGridModule } from 'ag-grid-angular';
import { TotalValueRendererMenu } from './cellRenderer.component';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import {MatCheckboxModule} from '@angular/material/checkbox';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import {MatTooltipModule} from '@angular/material/tooltip';
import {MatSlideToggleModule} from '@angular/material/slide-toggle';
import {MatTabsModule} from '@angular/material/tabs';
import { MatSelectModule } from '@angular/material/select';
import { NavItems } from '../../../ui/components/inner-nav.component';
import { GlobalVariable } from '../../../core/services/global.service';



@Component({
  selector: 'app-import-export-container',
  standalone: true,
  imports: [FormsModule, CommonModule, AgGridModule, MatMenuModule, MatExpansionModule,
    MatButtonModule,MatIconModule, MatCheckboxModule, MatFormFieldModule, MatInputModule,
    MatTooltipModule, MatSlideToggleModule, MatTabsModule, NavItems, MatSelectModule],
  templateUrl: './import-export-container-detail.component.html'
}) 
export class ImportExportContainerDetailComponent { 
  @ViewChild("agGrid") agGrid: AgGridAngular | undefined;
  detailFlag:boolean = false;
  columnDefs: any;
  rowSelection: any;
  defaultColDef: any;
  isfilter: boolean = true;
  gridApi: any;
  gidColumnApi: any;
  getpaged: any;
  gridOptions: any;
  cols: { field: string; header: string; }[];
  products: { ORDER_DATE: string; S_NO: number; GR_WT: number; PU_TVA: string; DP_TVA: string; VESSEL_PORT: string; ORDER_NO: string; PORT: string; VESSEL_DATE: string; BILLTO: string; VESSEL_NO: string; SPOT_LANE: string; DP_DATE: string; PU_LFD: string; DP_LFD: string; BL_NO: string; CONTAINER_NOTES: string; STATUS: string; DROP_AT: string; DRIVER: string; TRUCK: string; CHASSIS: string; LOAD: string; TYPE: string; SIZE: number; DP_TIME: string; SHIP_LINE: string; PU_DATE: string; PU_RES_NO: string; DP_RES_DATE: string; PU_RES_DATE: string; DP_RES_NO: string; PU_TIME: string; LEG_1_PICKUP: string; LEG1_DELIVER: string; LEG_2_PICKUP: string; LEG2_DELIVER: string; SEAL: string; }[];
  sidebarFlag: boolean = false;
  gridColumnApi: any;

  btnClick(fieldName:any, event:any) {
    let col = this.gridApi.getColumn(fieldName);
    if (event.checked) {
      this.gridApi.setColumnVisible(col, col.visible = true );
    } else {
      this.gridApi.setColumnVisible(col, col.visible = false);
    }
  }

  constructor(public gl: GlobalVariable) {
    
    this.columnDefs = [
      { field: 'S_NO', headerName: ' S. NO.', width: 95,  
      headerCheckboxSelection: true,
      checkboxSelection: true,
      sortingOrder: ["asc", "desc"],
      pinned: 'left'},
      {field: 'action', headerName: 'Action',   cellRenderer: TotalValueRendererMenu,  pinned: 'left',  width: 105,  },
    { field: 'GR_WT', headerName: 'GR WT', width: 140,},
    { field: 'PU_TVA', headerName: 'PU TVA', width: 140,   editable: true},
    { field: 'DP_TVA', headerName: 'DP TVA', width: 140,   editable: true},
    { field: 'VESSEL_PORT', headerName: ' VESSEL/PORT', width: 140,   editable: true},
    { field: 'ORDER_NO', headerName: '  ORDER NO', width: 140, editable: true},
    { field: 'PORT', headerName: 'PORT', width: 140, editable: true},
    { field: 'VESSEL_DATE', headerName: 'VESSEL DATE', width: 140, editable: true},
    { field: 'BILLTO', headerName: 'BILLTO' , width: 140, editable: true},
    { field: 'VESSEL_NO', headerName: 'VESSEL NO' , width: 140, editable: true},
    { field: 'SPOT_LANE', headerName: 'SPOT LANE' , width: 140, editable: true},
    { field: 'DP_DATE', headerName: 'DP DATE' , width: 140, editable: true}, 
    { field: 'PU_LFD', headerName: 'PU LFD' , width: 140, editable: true},
    { field: 'DP_LFD', headerName: 'DP LFD' , width: 140, editable: true},
    { field: 'BL_NO', headerName: 'BL NO' , width: 140, editable: true},
    { field: 'CONTAINER_NOTES', headerName: 'CONTAINER NOTES' , width: 140, editable: true},
    { field: 'STATUS', headerName: 'STATUS' , width: 140, editable: true},
    { field: 'DROP_AT', headerName: 'DROP AT' , width: 140, editable: true},
    { field: 'DRIVER', headerName: 'DRIVER' , width: 140, editable: true},
    { field: 'TRUCK', headerName: 'TRUCK' , width: 140, editable: true},
    { field: 'CHASSIS', headerName: 'CHASSIS' , width: 140, editable: true},
    { field: 'LOAD', headerName: 'LOAD' , width: 140, editable: true},
    { field: 'TYPE', headerName: 'TYPE' , width: 140, editable: true},
    { field: 'SIZE', headerName: 'SIZE' , width: 140, editable: true},
    { field: 'DP_TIME', headerName: 'DP TIME' , width: 140, editable: true},
    { field: 'SHIP_LINE', headerName: 'SHIP LINE' , width: 140, editable: true},
    { field: 'PU_DATE', headerName: 'PU DATE' , width: 140, editable: true},
    { field: 'PU_RES_NO', headerName: 'PU RES NO' , width: 140, editable: true},
    { field: 'DP_RES_DATE', headerName: 'DP RES DATE' , width: 140, editable: true},
    { field: 'PU_RES_DATE', headerName: 'PU RES DATE' , width: 140, editable: true},
    { field: 'DP_RES_NO', headerName: 'DP RES NO' , width: 140, editable: true},
    { field: 'PU_TIME', headerName: 'PU TIME' , width: 140, editable: true},
    { field: 'LEG_1_PICKUP', headerName: 'LEG 1 PICKUP' , width: 140, editable: true},
    { field: 'LEG1_DELIVER', headerName: 'LEG1 DELIVER' , width: 140, editable: true},
    { field: 'LEG_2_PICKUP', headerName: 'LEG 2 PICKUP' , width: 140, editable: true},
    { field: 'LEG2_DELIVER', headerName: 'LEG2 DELIVER' , width: 140, editable: true},
    { field: 'SEAL', headerName: 'SEAL No' , width: 140, editable: true},
    { width: 70}
     
    ];
    this.rowSelection = "multiple";

    this.defaultColDef = {
      editable: false,
      resizable: true,
      filter: true,
    };

    this.products = [
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 1,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 2,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 3,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 4,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 5,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 6,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 7,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 8,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 9,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 10,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 11,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 12,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 13,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 14,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 15,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 16,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 17,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 18,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 19,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 20,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 21,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 22,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 23,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 24,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 25,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 26,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 27,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 28,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 29,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 30,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 31,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 32,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 33,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 34,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 35,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 36,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 37,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 38,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 39,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 40,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 41,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 42,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 43,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 44,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 45,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 46,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 47,
        "GR_WT": 1500,
        "PU_TVA": "GHI789",
        "DP_TVA": "RST123",
        "VESSEL_PORT": "Ship3/Port3",
        "ORDER_NO": "ORD003",
        "PORT": "Port3",
        "VESSEL_DATE": "2023-12-03",
        "BILLTO": "Company3",
        "VESSEL_NO": "Ship3",
        "SPOT_LANE": "Lane3",
        "DP_DATE": "2023-12-07",
        "PU_LFD": "2023-12-02",
        "DP_LFD": "2023-12-06",
        "BL_NO": "BL003",
        "CONTAINER_NOTES": "C003 / Hazardous",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse3",
        "DRIVER": "Bob",
        "TRUCK": "T003",
        "CHASSIS": "CH003",
        "LOAD": "L003",
        "TYPE": "Flatrack",
        "SIZE": 20,
        "DP_TIME": "12:00",
        "SHIP_LINE": "SL003",
        "PU_DATE": "2023-12-01",
        "PU_RES_NO": "PR003",
        "DP_RES_DATE": "2023-12-05",
        "PU_RES_DATE": "2023-11-30",
        "DP_RES_NO": "DR003",
        "PU_TIME": "11:00",
        "LEG_1_PICKUP": "Port3",
        "LEG1_DELIVER": "Warehouse3",
        "LEG_2_PICKUP": "Warehouse3",
        "LEG2_DELIVER": "Port4",
        "SEAL": "S003"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 48,
        "GR_WT": 2500,
        "PU_TVA": "JKL123",
        "DP_TVA": "OPQ456",
        "VESSEL_PORT": "Ship4/Port4",
        "ORDER_NO": "ORD004",
        "PORT": "Port4",
        "VESSEL_DATE": "2023-12-04",
        "BILLTO": "Company4",
        "VESSEL_NO": "Ship4",
        "SPOT_LANE": "Lane4",
        "DP_DATE": "2023-12-08",
        "PU_LFD": "2023-12-03",
        "DP_LFD": "2023-12-07",
        "BL_NO": "BL004",
        "CONTAINER_NOTES": "C004 / Oversized",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse4",
        "DRIVER": "Alice",
        "TRUCK": "T004",
        "CHASSIS": "CH004",
        "LOAD": "L004",
        "TYPE": "Open Top",
        "SIZE": 40,
        "DP_TIME": "13:00",
        "SHIP_LINE": "SL004",
        "PU_DATE": "2023-12-02",
        "PU_RES_NO": "PR004",
        "DP_RES_DATE": "2023-12-06",
        "PU_RES_DATE": "2023-12-01",
        "DP_RES_NO": "DR004",
        "PU_TIME": "12:00",
        "LEG_1_PICKUP": "Port4",
        "LEG1_DELIVER": "Warehouse4",
        "LEG_2_PICKUP": "Warehouse4",
        "LEG2_DELIVER": "Port5",
        "SEAL": "S004"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 49,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001"
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 50,
        "GR_WT": 2000,
        "PU_TVA": "DEF456",
        "DP_TVA": "UVW789",
        "VESSEL_PORT": "Ship2/Port2",
        "ORDER_NO": "ORD002",
        "PORT": "Port2",
        "VESSEL_DATE": "2023-12-02",
        "BILLTO": "Company2",
        "VESSEL_NO": "Ship2",
        "SPOT_LANE": "Lane2",
        "DP_DATE": "2023-12-06",
        "PU_LFD": "2023-12-01",
        "DP_LFD": "2023-12-05",
        "BL_NO": "BL002",
        "CONTAINER_NOTES": "C002 / Heavy",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse2",
        "DRIVER": "Mary",
        "TRUCK": "T002",
        "CHASSIS": "CH002",
        "LOAD": "L002",
        "TYPE": "Reefer",
        "SIZE": 40,
        "DP_TIME": "11:00",
        "SHIP_LINE": "SL002",
        "PU_DATE": "2023-11-30",
        "PU_RES_NO": "PR002",
        "DP_RES_DATE": "2023-12-04",
        "PU_RES_DATE": "2023-11-29",
        "DP_RES_NO": "DR002",
        "PU_TIME": "10:00",
        "LEG_1_PICKUP": "Port2",
        "LEG1_DELIVER": "Warehouse2",
        "LEG_2_PICKUP": "Warehouse2",
        "LEG2_DELIVER": "Port3",
        "SEAL": "S002"
      },
     
    ]; 
  
  
    this.cols = [
      { field: 'S_NO', header: ' S. NO.'},
      { field: 'GR_WT', header: 'GR WT'},
      { field: 'PU_TVA', header: 'PU TVA'},
      { field: 'DP_TVA', header: 'DP TVA'},
      { field: 'VESSEL_PORT', header: ' VESSEL/PORT'},
      { field: 'ORDER_NO', header: '  ORDER NO'},
      { field: 'PORT', header: 'PORT'},
      { field: 'VESSEL_DATE', header: 'VESSEL DATE'},
      { field: 'BILLTO', header: 'BILLTO' },
      { field: 'VESSEL_NO', header: 'VESSEL NO' },
      { field: 'SPOT_LANE', header: 'SPOT LANE' },
      { field: 'DP_DATE', header: 'DP DATE' },
      { field: 'PU_LFD', header: 'PU LFD' },
      { field: 'DP_LFD', header: 'DP LFD' },
      { field: 'BL_NO', header: 'BL NO' },
      { field: 'CONTAINER_NOTES', header: 'CONTAINER NOTES' },
      { field: 'STATUS', header: 'STATUS' },
      { field: 'DROP_AT', header: 'DROP AT' },
      { field: 'DRIVER', header: 'DRIVER' },
      { field: 'TRUCK', header: 'TRUCK' },
      { field: 'CHASSIS', header: 'CHASSIS' },
      { field: 'LOAD', header: 'LOAD' },
      { field: 'TYPE', header: 'TYPE' },
      { field: 'SIZE', header: 'SIZE' },
      { field: 'DP_TIME', header: 'DP TIME' },
      { field: 'SHIP_LINE', header: 'SHIP LINE' },
      { field: 'PU_DATE', header: 'PU DATE' },
      { field: 'PU_RES_NO', header: 'PU RES NO' },
      { field: 'DP_RES_DATE', header: 'DP RES DATE' },
      { field: 'PU_RES_DATE', header: 'PU RES DATE' },
      { field: 'DP_RES_NO', header: 'DP RES NO' },
      { field: 'PU_TIME', header: 'PU TIME' },
      { field: 'LEG_1_PICKUP', header: 'LEG 1 PICKUP' },
      { field: 'LEG1_DELIVER', header: 'LEG1 DELIVER' },
      { field: 'LEG_2_PICKUP', header: 'LEG 2 PICKUP' },
      { field: 'LEG2_DELIVER', header: 'LEG2 DELIVER' },
      { field: 'SEAL', header: 'SEAL No' },
    ];

    this.getpaged = this.products
  }

  ngOnInit(): void {
    
  }
  selectedColumns!: any[];
  


   // AG GRID


   onFilterChanged() {
    let temp = this.gridApi.getFilterModel();

    if (Object.keys(this.gridApi.getFilterModel()).length > 0) {
      this.isfilter = true;
    }
    else {
      this.isfilter = false
    }
  }

  onGridReady(params: any) {
    this.gridOptions = params;
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    // let dataValue = [{ "name": "John", "type": "supplier", "email": "kuljeetkhalsa13@gmail.com", "phone": 9915970299, "address": "2phase-Mohali", "contactperson": "Baljit Singh", "created": "10/05/2020" }, { "name": "John", "type": "supplier", "email": "kuljeetkhalsa13@gmail.com", "phone": 9915970299, "address": "2phase-Mohali", "contactperson": "Baljit Singh", "created": "10/05/2020" },]
    // params.api.setRowData(this.getpaged);
    params.api.setGridOption('rowData', this.getpaged);
  }

  onSelectionChanged() {
    this.gl.setRowData = null;
    const selectedNodes = this.agGrid?.api.getSelectedNodes();
    const selectedData: any = selectedNodes?.map((node:any) => node.data);
    this.gl.setRowData = JSON.stringify(selectedData[0])
      ? selectedData[0]
      : null;

    if (this.gl.setRowData) {
      this.detailFlag = true
    }
  } 


}