import { Component, HostListener, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AgGridAngular, AgGridModule } from 'ag-grid-angular';
import { TotalValueRendererMenu } from './cellRenderer.component';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import {MatCheckboxModule} from '@angular/material/checkbox';
import { animate, state, style, transition, trigger } from '@angular/animations';
import { MatFormField, MatFormFieldModule } from '@angular/material/form-field';
import {MatSelectModule} from '@angular/material/select';
import { MatInputModule } from '@angular/material/input';
import {MatDatepickerModule} from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core';
import { SearchDriverLog } from './slides/search.component';
import { AddNewLogComponent } from './slides/addNewLog.component';
import { BackToYardComponent } from './slides/backToYard.component';
import { DoneForDayComponent } from './slides/doneForDay.component';
import { GlobalVariable } from '../../core/services/global.service';


@Component({
  selector: 'app-driver-log',
  standalone: true,
  imports: [FormsModule, CommonModule, AgGridModule, MatMenuModule,
    MatButtonModule,MatIconModule, MatCheckboxModule, AddNewLogComponent,
    FormsModule, MatFormFieldModule, MatSelectModule, MatInputModule, MatDatepickerModule,
    MatNativeDateModule, SearchDriverLog, BackToYardComponent, DoneForDayComponent ],
  templateUrl: './driver-log.component.html',
  animations: [
    trigger('openCloseSearch', [
      state('true', style({ right: '0' })),
      state('false', style({ right: '-450px' })),
      transition('false <=> true', animate(250))
    ]),
    trigger('openCloseAdd', [
      state('true', style({ right: '0' })),
      state('false', style({ right: '-850px' })),
      transition('false <=> true', animate(250))
    ]),

  ],
}) 
export class DriverLogComponent { 
  detailFlag: boolean = false;
  addRowFlag: boolean = false;
  searchFlag: boolean = false;
  backToYard: boolean = false;
  doneForDay: boolean = false;
  slideArray = [this.addRowFlag, this.searchFlag, this.backToYard, this.doneForDay];
  @ViewChild("agGrid") agGrid: AgGridAngular | undefined;
  @HostListener('document:keydown.escape', ['$event']) onKeydownHandler(event: KeyboardEvent) {
    this.detailFlag = false;
    this.addRowFlag = false;
    this.searchFlag = false;
    this.backToYard = false;
    this.doneForDay = false;
  }
  columnDefs: any;
  rowSelection: any;
  defaultColDef: any;
  isfilter: boolean = true;
  gridApi: any;
  gidColumnApi: any;
  getpaged: any;
  gridOptions: any;
  cols: { field: string; header: string; }[];
  products: { ORDER_DATE: string; Leg_type:string; status:string; S_NO: number; GR_WT: number; PU_TVA: string; DP_TVA: string; VESSEL_PORT: string; ORDER_NO: string; PORT: string; VESSEL_DATE: string; BILLTO: string; VESSEL_NO: string; SPOT_LANE: string; DP_DATE: string; PU_LFD: string; DP_LFD: string; BL_NO: string; CONTAINER_NOTES: string; STATUS: string; DROP_AT: string; DRIVER: string; TRUCK: string; CHASSIS: string; LOAD: string; TYPE: string; SIZE: number; DP_TIME: string; SHIP_LINE: string; PU_DATE: string; PU_RES_NO: string; DP_RES_DATE: string; PU_RES_DATE: string; DP_RES_NO: string; PU_TIME: string; LEG_1_PICKUP: string; LEG1_DELIVER: string; LEG_2_PICKUP: string; LEG2_DELIVER: string; SEAL: string; }[];
  sidebarFlag: boolean = false;
  gridColumnApi: any;

  btnClick(fieldName:any, event:any) {
    let col = this.gridApi.getColumn(fieldName);
    if (event.checked) {
      this.gridApi.setColumnVisible(col, col.visible = true );
    } else {
      this.gridApi.setColumnVisible(col, col.visible = false);
    }
  }

  constructor(public gl: GlobalVariable) {
    
    this.columnDefs = [
      { 
        field: 'S_NO', headerName: ' S. NO.', width: 85,  
        headerCheckboxSelection: true,
        checkboxSelection: true,
        sortingOrder: ["asc", "desc"],
        pinned: 'left'
      },
      { field: 'action', headerName: 'Action',   cellRenderer: TotalValueRendererMenu,  pinned: 'left',  width: 90,  },
      { field: 'DRIVER', headerName: 'Driver', width: 110, editable: true},
      { field: 'VESSEL_DATE', headerName: 'Date', width: 140,},
      { field: 'DP_DATE', headerName: 'Login At' , width: 100, editable: true},
      { field: 'TRUCK', headerName: 'Truck' , width: 120, editable: true},
      { field: 'VESSEL_DATE', headerName: 'Logout At' , width: 140, editable: true},
      { field: 'DP_TIME', headerName: 'Login Time' , width: 110, editable: true},
      { field: 'GR_WT', headerName: 'Payroll Amt' , width: 110, editable: true},
      { width: 70}
    ];
    this.rowSelection = "multiple";

    this.defaultColDef = {
      editable: false,
      resizable: true,
      filter: true,
    };

    this.products = [
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 1,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 2,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 3,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 4,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 5,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 6,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 7,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 8,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 9,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 10,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 11,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 12,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 13,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 14,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 15,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 16,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 17,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 18,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 19,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 20,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 21,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 22,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 23,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 24,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 25,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 26,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 27,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 28,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 29,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 30,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 31,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
      {
        "ORDER_DATE": "2023-11-28",
        "S_NO": 31,
        "GR_WT": 1000,
        "PU_TVA": "ABC123",
        "DP_TVA": "XYZ456",
        "VESSEL_PORT": "Ship1/Port1",
        "ORDER_NO": "ORD001",
        "PORT": "Port1",
        "VESSEL_DATE": "2023-12-01",
        "BILLTO": "Company1",
        "VESSEL_NO": "Ship1",
        "SPOT_LANE": "Lane1",
        "DP_DATE": "2023-12-05",
        "PU_LFD": "2023-11-30",
        "DP_LFD": "2023-12-04",
        "BL_NO": "BL001",
        "CONTAINER_NOTES": "C001 / Fragile",
        "STATUS": "In Transit",
        "DROP_AT": "Warehouse1",
        "DRIVER": "John",
        "TRUCK": "T001",
        "CHASSIS": "CH001",
        "LOAD": "L001",
        "TYPE": "Dry",
        "SIZE": 20,
        "DP_TIME": "10:00",
        "SHIP_LINE": "SL001",
        "PU_DATE": "2023-11-29",
        "PU_RES_NO": "PR001",
        "DP_RES_DATE": "2023-12-03",
        "PU_RES_DATE": "2023-11-28",
        "DP_RES_NO": "DR001",
        "PU_TIME": "09:00",
        "LEG_1_PICKUP": "Port1",
        "LEG1_DELIVER": "Warehouse1",
        "LEG_2_PICKUP": "Warehouse1",
        "LEG2_DELIVER": "Port2",
        "SEAL": "S001",
        'Leg_type': 'Complete',
        'status': 'New',
      },
     
    ]; 
  
  
    this.cols = [
      { field: 'S_NO', header: ' S. NO.'},
      { field: 'GR_WT', header: 'GR WT'},
      { field: 'PU_TVA', header: 'PU TVA'},
      { field: 'DP_TVA', header: 'DP TVA'},
      { field: 'VESSEL_PORT', header: ' VESSEL/PORT'},
      { field: 'ORDER_NO', header: '  ORDER NO'},
      { field: 'PORT', header: 'PORT'},
      { field: 'VESSEL_DATE', header: 'VESSEL DATE'},
      { field: 'BILLTO', header: 'BILLTO' },
      { field: 'VESSEL_NO', header: 'VESSEL NO' },
      { field: 'SPOT_LANE', header: 'SPOT LANE' },
      { field: 'DP_DATE', header: 'DP DATE' },
      { field: 'PU_LFD', header: 'PU LFD' },
      { field: 'DP_LFD', header: 'DP LFD' },
      { field: 'BL_NO', header: 'BL NO' },
      { field: 'CONTAINER_NOTES', header: 'CONTAINER NOTES' },
      { field: 'STATUS', header: 'STATUS' },
      { field: 'DROP_AT', header: 'DROP AT' },
      { field: 'DRIVER', header: 'DRIVER' },
      { field: 'TRUCK', header: 'TRUCK' },
      { field: 'CHASSIS', header: 'CHASSIS' },
      { field: 'LOAD', header: 'LOAD' },
      { field: 'TYPE', header: 'TYPE' },
      { field: 'SIZE', header: 'SIZE' },
      { field: 'DP_TIME', header: 'DP TIME' },
      { field: 'SHIP_LINE', header: 'SHIP LINE' },
      { field: 'PU_DATE', header: 'PU DATE' },
      { field: 'PU_RES_NO', header: 'PU RES NO' },
      { field: 'DP_RES_DATE', header: 'DP RES DATE' },
      { field: 'PU_RES_DATE', header: 'PU RES DATE' },
      { field: 'DP_RES_NO', header: 'DP RES NO' },
      { field: 'PU_TIME', header: 'PU TIME' },
      { field: 'LEG_1_PICKUP', header: 'LEG 1 PICKUP' },
      { field: 'LEG1_DELIVER', header: 'LEG1 DELIVER' },
      { field: 'LEG_2_PICKUP', header: 'LEG 2 PICKUP' },
      { field: 'LEG2_DELIVER', header: 'LEG2 DELIVER' },
      { field: 'SEAL', header: 'SEAL No' },
    ];

    this.getpaged = this.products
  }

  ngOnInit(): void {
    
  }
  selectedColumns!: any[];
  


   // AG GRID


   onFilterChanged() {
    let temp = this.gridApi.getFilterModel();

    if (Object.keys(this.gridApi.getFilterModel()).length > 0) {
      this.isfilter = true;
    }
    else {
      this.isfilter = false
    }
  }

  onGridReady(params: any) {
    this.gridOptions = params;
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;
    // let dataValue = [{ "name": "John", "type": "supplier", "email": "kuljeetkhalsa13@gmail.com", "phone": 9915970299, "address": "2phase-Mohali", "contactperson": "Baljit Singh", "created": "10/05/2020" }, { "name": "John", "type": "supplier", "email": "kuljeetkhalsa13@gmail.com", "phone": 9915970299, "address": "2phase-Mohali", "contactperson": "Baljit Singh", "created": "10/05/2020" },]
    // params.api.setRowData(this.getpaged);
    params.api.setGridOption('rowData', this.getpaged);
  }

  onSelectionChanged() {
    this.gl.setRowData = null;
    const selectedNodes = this.agGrid?.api.getSelectedNodes();
    const selectedData: any = selectedNodes?.map((node:any) => node.data);
    this.gl.setRowData = JSON.stringify(selectedData[0])
      ? selectedData[0]
      : null;

    if (this.gl.setRowData) {
      this.detailFlag = true
    }
  } 

  blackOutFalse() {
    this.addRowFlag = false;
    this.searchFlag = false;
    this.backToYard = false;
    this.doneForDay = false;
  }
  
}